version: '3'
silent: true

# Ordered lists determine execution order
pre:
  - setup_dns
  - check_targets

post:
  - verify_harbor
  - notify

# Define the actual task implementations here
tasks:
  setup_dns:
    desc: "Set up DNS entries"
    cmds:
      - bash -lc 'echo "[pre] setting DNS..."'

  check_targets:
    desc: "Check target hosts"
    cmds:
      - bash -lc 'echo "[pre] pinging hosts..."'

  verify_harbor:
    desc: "Verify Harbor is responding"
    cmds:
      - bash -lc 'echo "[post] checking harbor..."'

  notify:
    desc: "Send notification"
    cmds:
      - bash -lc 'echo "[post] notifying team..."'
