#------------------------------------------------------------------------------  
# 1) Core Environment
#------------------------------------------------------------------------------
ssh_user: "kratos"

rke2_network:
  cidr: "10.0.0.0/24"         # base/installation network for nodes
  gateway: "10.0.0.1"
  dns:
    servers:
      - "10.0.0.52"
      - "10.0.0.53"
    domain_name:
      - "example.local"
  ntp:
    servers:
      - "10.0.0.52"
      - "10.0.0.53"

#------------------------------------------------------------------------------  
# 2) Platform & Registry Selection
#------------------------------------------------------------------------------
kubernetes_platform: "rancher"
#kubernetes_platform: "eks"

container_registry: "harbor"
#container_registry: "ecr"

#------------------------------------------------------------------------------  
# 3) Registry Configuration
#------------------------------------------------------------------------------
registry_config:

  harbor:
    url: "harbor.ops.example.local"
    project: "onboarder"
    robot_account:
      username: "robot$onboarder"
      password: "{{ vault_harbor_robot_password }}"   # reference to your vault
    insecure: false

  ecr:
    aws_account_id: "123456789012"
    region: "us-east-2"
    repository: "onboarder"
    iam_role_arn: "arn:aws:iam::123456789012:role/ECRPushPull"

#------------------------------------------------------------------------------  
# 4) Clusters & Nodes
#------------------------------------------------------------------------------
# mcms/osms/osdc are lists. Each item lets you scale up/down freely.
# name is your cluster/logical node name; ip is the node’s primary IP on rke2_network.
mcms:
  cluster_name: "mcm-cluster"
  nodes:
    - { name: "mcm1", ip: "10.0.0.110" }
    - { name: "mcm2", ip: "10.0.0.111" }
    - { name: "mcm3", ip: "10.0.0.112" }

osms:
  cluster_name: "osms-cluster"
  nodes:
    - { name: "osms1", ip: "10.0.0.113" }
    - { name: "osms2", ip: "10.0.0.114" }
    - { name: "osms3", ip: "10.0.0.115" }

osdc:
  cluster_name: "osdc-cluster"
  nodes:
    - { name: "osdc1", ip: "10.0.0.116" }
    - { name: "osdc2", ip: "10.0.0.117" }
    - { name: "osdc3", ip: "10.0.0.118" }